# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/my_cpu/_Build_CPU/constraint/nexys_pin.xdc

# IP: ip/kernel_code/kernel_code.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kernel_code || ORIG_REF_NAME==kernel_code} -quiet] -quiet
