# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/my_cpu/_Build_CPU/xpr_monitor/project_1.cache/wt [current_project]
set_property parent.project_path D:/my_cpu/_Build_CPU/xpr_monitor/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/my_cpu/_Build_CPU/xpr_monitor/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/my_cpu/_Build_CPU/kernel/supervisor_v2.01/kernel/kernel_mod.coe
read_verilog {
  D:/my_cpu/_Build_CPU/code_monitor/bus.h
  D:/my_cpu/_Build_CPU/code_monitor/define.h
}
set_property file_type "Verilog Header" [get_files D:/my_cpu/_Build_CPU/code_monitor/bus.h]
set_property file_type "Verilog Header" [get_files D:/my_cpu/_Build_CPU/code_monitor/define.h]
read_verilog -library xil_defaultlib -sv {
  D:/my_cpu/_Build_CPU/code_monitor/async.sv
  D:/my_cpu/_Build_CPU/code_monitor/bram_kernel_code.sv
  D:/my_cpu/_Build_CPU/code_monitor/bram_kernel_data.sv
  D:/my_cpu/_Build_CPU/code_monitor/bram_user_code.sv
  D:/my_cpu/_Build_CPU/code_monitor/bram_user_data.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_addr_dec_custom.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_arbiter_custom.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_cpu_bram.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_mux_custom.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_slave_mux_custom.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_sum_custom.sv
  D:/my_cpu/_Build_CPU/code_monitor/bus_top.sv
  D:/my_cpu/_Build_CPU/code_monitor/define.sv
  D:/my_cpu/_Build_CPU/code_monitor/mips_top.sv
  D:/my_cpu/_Build_CPU/code_monitor/reg_exemem.sv
  D:/my_cpu/_Build_CPU/code_monitor/reg_idexe.sv
  D:/my_cpu/_Build_CPU/code_monitor/reg_ifid.sv
  D:/my_cpu/_Build_CPU/code_monitor/reg_memwb.sv
  D:/my_cpu/_Build_CPU/code_monitor/regfile.sv
  D:/my_cpu/_Build_CPU/code_monitor/stage_exe.sv
  D:/my_cpu/_Build_CPU/code_monitor/stage_id.sv
  D:/my_cpu/_Build_CPU/code_monitor/stage_if.sv
  D:/my_cpu/_Build_CPU/code_monitor/stage_mem.sv
  D:/my_cpu/_Build_CPU/code_monitor/stall.sv
  D:/my_cpu/_Build_CPU/code_monitor/uart_ctrl.sv
  D:/my_cpu/_Build_CPU/code_monitor/uart_sum.sv
  D:/my_cpu/_Build_CPU/code_monitor/thinpad_top.sv
}
read_ip -quiet D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/kernel_code/kernel_code.xci
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/kernel_code/kernel_code_ooc.xdc]

read_ip -quiet D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_data/user_data.xci
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_data/user_data_ooc.xdc]

read_ip -quiet D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code.xci
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code_ooc.xdc]

read_ip -quiet D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/kernel_data/kernel_data.xci
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/kernel_data/kernel_data_ooc.xdc]

read_ip -quiet D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/pll_example/pll_example.xci
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/pll_example/pll_example_board.xdc]
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/pll_example/pll_example.xdc]
set_property used_in_implementation false [get_files -all d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/my_cpu/_Build_CPU/constraint/nexys_pin.xdc
set_property used_in_implementation false [get_files D:/my_cpu/_Build_CPU/constraint/nexys_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top thinpad_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef thinpad_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file thinpad_top_utilization_synth.rpt -pb thinpad_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
