# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/my_cpu/chap4_simu/xpr/project_1.srcs/sources_1/ip/kernel_data/kernel_data.xci
# IP: The module: 'kernel_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_cpu/chap4_simu/xpr/project_1.srcs/sources_1/ip/kernel_data/kernel_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kernel_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/my_cpu/chap4_simu/xpr/project_1.srcs/sources_1/ip/kernel_data/kernel_data.xci
# IP: The module: 'kernel_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_cpu/chap4_simu/xpr/project_1.srcs/sources_1/ip/kernel_data/kernel_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kernel_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
