# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code.xci
# IP: The module: 'user_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_code'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code.xci
# IP: The module: 'user_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_cpu/_Build_CPU/xpr_monitor/project_1.srcs/sources_1/ip/user_code/user_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_code'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
